import localFont from "next/font/local";
import "../globals.css";



export const metadata = {
  title: "register",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <>
                {children}
        </>


  );
}
